---
- include: redhat.yml
  when: ansible_os_family == 'RedHat'

- include: debian.yml
  when: ansible_os_family == 'Debian'

- name: create filebeat.yml
  template:
    src: filebeat.yml.j2
    dest: /etc/filebeat/filebeat.yml
  notify:
    - restart filebeat

- name: copy ca certificate if required
  copy:
    content: "{{ filebeat_ca_cert }}"
    dest: "{{ filebeat_ca_path }}"
    owner: root
    group: root
    mode: 0400
  when: filebeat_ca_cert != None

- name: copy ssl certificate if required
  copy:
    content: "{{ filebeat_ssl_cert }}"
    dest: "{{ filebeat_ssl_cert_path }}"
    owner: root
    group: root
    mode: 0400
  when: filebeat_ssl_cert != None

- name: copy ssl key if required
  copy:
    content: "{{ filebeat_ssl_key }}"
    dest: "{{ filebeat_ssl_key_path }}"
    owner: root
    group: root
    mode: 0400
  when: filebeat_ssl_key != None

- name: flush handlers to prevent start then restart
  meta: flush_handlers

- name: check if systemd present
  stat:
    path: /bin/systemctl
  register: stat_result

- name: reload systemd daemon
  shell: "systemctl daemon-reload"
  when: stat_result.stat.exists == true

- name: enable filebeat
  service:
    name: filebeat
    enabled: true

- name: start filebeat
  service:
    name: filebeat
    state: started
  when: start_services
