---
- name: add rpm key for elastic.co
  rpm_key:
    key: "{{ filebeat_gpg_url }}"

- name: create beats yum repo
  yumrepo:
    name: beats
    baseurl: "{{ filebeat_repo_url }}"
    enabled: yes
    gpgcheck: yes
    gpgkey: "{{ filebeat_gpg_url }}"

- name: install filebeat
  yum:
    name: "filebeat-{{ filebeat_version }}"
    state: present
  notify:
    - restart filebeat

- name: modify filebeat service file to include environment variables
  lineinfile:
    path: /usr/lib/systemd/system/filebeat.service
    regexp: '^EnvironmentFile=/etc/sysconfig/filebeat$'
    line: "EnvironmentFile=/etc/sysconfig/filebeat"
    insertafter: '^\[Service\]$'
  notify:
    - restart filebeat
